language: node_js
node_js:
- '8'
sudo: required
services:
- docker
branches:
  only:
  - master
env:
  global:
  - secure: yJb41HAOx+Nt19XmEghcrwWoC0fLF/DJ5MlD1RsRaFWcZlyvjT4Qm9iop8soqPXavlkOr40pk1CJck8zzwx3/wh8OBhrPsgI2OHvgWN8tkqcmDm7k/q9yxrsKyEYxYyIqVSU8DgcPc9XzTPwR0sJjHe50Smgmcvi3zCAr3Ae+plzSuW0z6evH9wETC+u47dmJhLi5zN1VR1CZn6h418xRcns5r+3Qo6bpq2jzyjApG4QSm8CVbrzZHkZKo+QLv6z7vgmJlDc8Hj9mtgGoybJuQ7z4prRWPYDvs0Gaov5CP/NqE9ZicNqa2Oo4v5RPwIL8YOeksDaMJDBz8h5XrlIyhqIp7Gn5IlcRvkPr7pTMBNiZoQI/bahaSSms61gvz1Mqc103wEMgUifhTDAHhgNsHKM2DfqBlAE5AkDimP47dJhGhyDW3h+/ApMYTR4bIQrH91X3Tzsdsz8KSA/vBrdlvYejPQ0cOy3x6NMOsaqJ+EDw9RUE+xoA31WzJe7DxFDFFMJqi0yA3sGG1kjDUNXcJkj9IL3ijjMHNgBMQQg3S1Vk0bZVj7V/ry0wEXoWLfY5OIkp2i45rK2Nbym9IqmBAB2ZS8IU2j8QH0W8/rUfebTnDbfrzIlNzl3ikjBzeDFCo7Hp1bhKiRXJ74LZXtcE87BZvvVWnSCmNET7fNtI2Y=
  - secure: aczIlkQYDu4Na0e85bi9XoqOZjGdXrIL+KZlMM5YqlNEfFzuFam25UYT2ENWkWejvVYzjoSvQ13fhbSSimpDA5nvWn5Taeu/PHlmOV/UsAdvdyQkqijSMwxvUDOfd5YjQFzdDNMzcrSUG+kje8q7DcF52rX8c715VQ+rY4AWkPHtJhHFaTGoNUAE44x62jcitLHxh6NdVXMUlMqS/Hf9VOmzM0Vxy70bIS11a886roca5lpZattq9p/9jRmL3VcP4u8RuVxRqsAgC0MGm7f4ekHsKfxj5BzIdjG12xmPVbnjtubLIT2A3L2qkDhRDpkg3tbdvr6Bjtsatyvn9VKgyInKN7uZ7XhXrO2aZLsiUhGt6QnlGIZvepSqMWCGsp3KpYjjpccf5q5ub5mMpRbKOuapqKTOq2FZp10kpv7iTYiy4zlE8CQyzqU22qR+rsE+MEznr3n2/jkxMr4zvqCW4BsgZpnQOMXT2R4v1Y7B8++xG1SRfMAXMqx4UYwZpmWWu5DowUdfbF0rFjxxC87g1XbONQxGug7IV+zvOfeEZt27N8dQdzybO6POtw6uOM9DxG4O7vIwbE1bHSudIYFIEQnurEIuQG06Tla2+lqItnMQHQrivJ2pRVkzRjhp74p3Jo2b6ozFtdmIqKMpIr2yjd7MBsDKV0SXgj6X7VbQRzo=

jobs:
  include:
  - stage: Unit tests
    script: make unit-test
  - stage: Build docker
    script: make docker-lint docker-build docker-tag docker-push
    if: branch = master
